name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write
      actions: write
      packages: write
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Setup Python (for native dependencies)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
          
      - name: Install dependencies
        run: npm ci
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
          ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
          npm_config_cache: ${{ github.workspace }}/.cache/npm
          npm_config_prefer_offline: true
        
      - name: Install better-sqlite3
        run: npm install better-sqlite3@^9.2.2
        
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
        
      - name: Publish releases
        env:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
        run: npm run release
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: |
            release/*.exe
            release/*.dmg
            release/*.AppImage
            release/*.deb
            release/*.rpm
            release/*.snap
            release/*.tar.gz
            release/*.zip
          if-no-files-found: ignore